### ISSUE TITLE
周报

### ISSUE THREAD

**Issue by donghaiwang** [OpenHUTB/driving#1]
请按照下面格式每周写好周报

张三：2023.03.30~2023.04.6
本周工作总结：进行数据平台SDK及客户端开发测试，参与2.03需求开发
进展情况：1.修改原来的数据平台SDK的实现与需求不一致的情况，即和前端web功能不一致的情况；-close
                  2.进行最新实现功能的自测；-close
                  3.提交修改后的代码进行测试；-50%
遇到的问题：1. 

下周工作计划：
任务：数据平台SDK
工作内容：1.监控并维护上线的数据SDK运行（3.7）；
                  2. 跟踪项目详情中可以看见每个数据ID进度的线上情况（3.7-3.9）；
                  3. 查看及参与标注平台2.04需求中的盘古工具链后端接口需求的开发（3.7-3.12）；

**Comment by champion123456** [comment]
张卫：2023.04.01-2023.04.07
本周工作：了解rouadRunner的基本使用，参与咸嘉新村于湖南工商大学重要路口的建模
进展：对两者进行了合并，小区以及大局道路建模等已基本完成。

下周工作：对湖南工商大学西门处路口--->湖南工商大学地铁口（桐梓坡路进行细小建模），以及房屋建模到达中上程度

**Comment by donghaiwang** [comment]
> 张卫：2023.04.01-2023.04.07 本周工作：了解rouadRunner的基本使用，参与咸嘉新村于湖南工商大学重要路口的建模 进展：对两者进行了合并，小区以及大局道路建模等已基本完成。
> 
> 下周工作：对湖南工商大学西门处路口--->湖南工商大学地铁口（桐梓坡路进行细小建模），以及房屋建模到达中上程度

1. 如果RoadRunner工程太大不好用git进行管理可以直接提供百度网盘链接到 [当前项目](https://github.com/OpenHUTB/driving) 的readme.md文件当中，插入到“场景->实现”内容中，并提交Pull Request；
2. 将进行场景构建的步骤和注意事项整理成一个.md文件添加到项目当中，以便其他人参与进来；
3. 杨子仪的周报是不是和你一起，如果不是她也要写周报。

**Comment by Gloria-ziyiyang** [comment]
杨子仪：2023.04.01~2023.04.07
本周工作总结：完善细致湖南工商大学附近道路与周边环境建设
进展情况：1.修改、继续完善roadruner建模，与实时地图保持一致；-50%
2.合并湖南工商大学、咸嘉新村两个模块；-close
下周工作计划：
任务：继续细化两部分除道路外的环境建设；学习如何自定义资产和导入。
工作内容：1.细节除道路外资产（4.8-4.12）；
2. 学习如何自定义资产和导入（4.12-4.14）；

**Comment by Gloria-ziyiyang** [comment]
杨子仪：2023.04.10~2023.04.14
本周工作总结：完善细致湖南工商大学附近道路与周边环境建设
进展情况：1.修改、继续完善建模，与实时地图保持一致；-60%
2.找各种素材，完善道路细节。
下周工作计划：
任务：继续找素材；完善周围环境，尽量让地图上没有黑块。
难点：素材有限，导致和实景地图差异还很大。

**Comment by champion123456** [comment]
张卫:2023.04.10~2023.04.14
本周进展：1.再次完善道路与道路物体部署
                   2.抠细节 争取与实景达一致
下周工作：
任务：争取将此路搭建完毕
难点：随材难以寻找，太精细了，用一下建模工具太陌生了，所以导致与实景差

**Comment by donghaiwang** [comment]
> 杨子仪：2023.04.10~2023.04.14 本周工作总结：完善细致湖南工商大学附近道路与周边环境建设 进展情况：1.修改、继续完善建模，与实时地图保持一致；-60% 2.找各种素材，完善道路细节。 下周工作计划： 任务：继续找素材；完善周围环境，尽量让地图上没有黑块。 难点：素材有限，导致和实景地图差异还很大。

自定义素材工作量确实比较大，除了百度提供的数据，可能还会需要实际采集一些数据；你们建模自定义素材使用的工具是什么

**Comment by Gloria-ziyiyang** [comment]
> > 杨子仪：2023.04.10~2023.04.14 本周工作总结：完善细致湖南工商大学附近道路与周边环境建设 进展情况：1.修改、继续完善建模，与实时地图保持一致；-60% 2.找各种素材，完善道路细节。 下周工作计划： 任务：继续找素材；完善周围环境，尽量让地图上没有黑块。 难点：素材有限，导致和实景地图差异还很大。
> 
> 自定义素材工作量确实比较大，除了百度提供的数据，可能还会需要实际采集一些数据；你们建模自定义素材使用的工具是什么


> > 杨子仪：2023.04.10~2023.04.14 本周工作总结：完善细致湖南工商大学附近道路与周边环境建设 进展情况：1.修改、继续完善建模，与实时地图保持一致； -60% 2.找各种素材，完善道路细节。 下周工作计划： 任务：继续找素材； 完善周围环境，尽量让地图上没有黑块。 难点：素材有限，导致和实景地图差异还很大。
> 
> 自定义素材工作量确实比较大，除了百度提供的数据，可能还会需要实际采集一些数据； 你们建模自定义素材使用的工具是什么

我们没有自己创建，在素材网上找的

**Comment by Gloria-ziyiyang** [comment]
杨子仪：2023.04.17~2023.04.21 
本周工作总结：完善道路细节，尝试导出
进展情况：1.导出失败，道路报错 2.大致学习了下虚幻引擎
下周工作计划：重新搭建道路，重头再来 ::>_<:: 继续了解虚幻引擎，拿小场景先做测试

**Comment by champion123456** [comment]
张卫：2023.04.17~2023.04.21
本周：细节完善，并尝试与虚拟引擎结合，---->失败,找原因 并根据后续进行改进
进展情况：出面导出大面积错误，以及了解虚拟引擎
下周工作计划：道路冲配置，并基于一小部分慢慢进行小场景测试

**Comment by Gloria-ziyiyang** [comment]
杨子仪：2023.04.21~2023.04.28
本周工作总结：roadrunner导出，ue4导入
进展情况：1.roadruner 导出成功，ue4导入成功，但有偏差 2.大致学习了下ue4的基本功能
难点：ue4不太会用，功能也比较多，学习过程长 
下周工作计划：学习ue4，调整导入以后的细节差，还有西二环下的路还要画

**Comment by champion123456** [comment]
张卫：04.21-04.28
本周工作总结:道路导出失败。问题太多，导致导出完全失败，大规模更改重来，进行与UE4联合
进展情况：1.目前项目能够导出到Ue4，希望后面细化下去不出错，偏差存在后续进行修改，2.了解UE+matlab进行联合仿真
难点：配置相对复杂，功能模块复杂，目前联合还不是很了解细节，以及后续细化难度提高
下周：学习联合，以及导入后的细节，其次是细中带细的细化，元素正在创造。。。

**Comment by donghaiwang** [comment]
> 张卫：04.21-04.28 本周工作总结:道路导出失败。问题太多，导致导出完全失败，大规模更改重来，进行与UE4联合 进展情况：1.目前项目能够导出到Ue4，希望后面细化下去不出错，偏差存在后续进行修改，2.了解UE+matlab进行联合仿真 难点：配置相对复杂，功能模块复杂，目前联合还不是很了解细节，以及后续细化难度提高 下周：学习联合，以及导入后的细节，其次是细中带细的细化，元素正在创造。。。

嗯，暂时主要精力先放在场景的细化上，这是后面所有工作的基础。
在搭建十字路口真实场景时可以了解项目的目的是和main.mlx文件（实现了红绿灯和车之间的通信和高位摄像头车辆的检测）进行对接，main.mlx可以和虚幻编辑器进行对接（目前的代码实现），也可以和[导出的可执行虚幻场景](https://ww2.mathworks.cn/help/driving/ug/package-custom-scenes-into-executable.html)进行对接。

**Comment by champion123456** [comment]
张卫：04.29-05.05 本周工作总结:道路初步导出成功。最终道路版还没有成功，稍作更改，再试试。进行与UE4联合，以及初步了解Matlab相关main， 
进展情况：1.目前项目能够导出到Ue4，最终道路版还没有成功，偏差存在后续进行修改，2.了解UE+matlab进行联合仿真 难点：配置相对复杂，功能模块复杂，目前联合还不是很了解细节，以及后续细化难度提高 
下周：导出，在UE进行其它元素更改，形成较好的初步样式。以及进行初步与main.mlx的联合

**Comment by Gloria-ziyiyang** [comment]
杨子仪：04.29-05.05 
本周工作总结:场景再次完善，导入ue4后出现表面碎片，暂时未找到解决方法
难点：电脑渲染很慢，出现碎片还不知道是电脑带不动渲染的原因还是没有设置好，网上也没有很多解决方案，上周导入是没问题的……
下周：再次尝试重新导入或者调整参数，继续完善场景

**Comment by Gloria-ziyiyang** [comment]
杨子仪：05.07-05.12
本周工作总结:服务器配环境，上传工程
下周：服务器上调整场景和细节

**Comment by champion123456** [comment]
张卫：05-05-05.12
本周：先对RoadRunner再次改进，由于之前导进去（错误较多，模糊），可能部分场景出错，然后进行改进，再进行导入
然后就是折磨人的服务器的环境的配置，以及服务器显示问题，以及上传问题。
下周：将Ue4.26与Matlab进行场景联动。可能这一部分还有问题，尝试了几次没有成功，还得再尝试。
难点：UE4.26感觉操作繁杂，要进行学习了解以及与Matlab进行联动。

**Comment by champion123456** [comment]
张卫：05-14  -05-19
本周：对之前的模型进行完善，然后完成导入，实现相对清晰，以及部分模块的细化，尝试将之前做的西门、北门进行导入，发现导入变形，损失，以及学习Ue的载具的实现，感觉功能相对繁杂。知识内容多
下周：继续尝试学习吧，上周阳了，没做很多的任务。下周继续尝试将其他模型导入，然后Ue的学习，看是否能实现载具的一个功能
难点：操作复杂，一步错感觉后面就出现不一样的效果，暂时有点卡壳啦

**Comment by Gloria-ziyiyang** [comment]
张卫：05-14 -05-19
本周：没做什么，写论文做实验去了😖
下周：再看下ue打开以后效果，做下场景调整吧，然后有空就看视频学下怎么做联合仿真
难点：Ue 不会操作，功能很复杂，学习起来也很累

**Comment by haiping-jpp** [comment]
蒋平平：05-26-06-02
下周：1.配置好matlab与CUDA环境；2.运行一个YOLOv4demo，将一段短视频中目标的坐标输出到txt文件中；3.学习目标跟踪方面的知识
