### ISSUE TITLE
问题如下

### ISSUE THREAD

**Issue by champion123456** [OpenHUTB/driving#2]
**问题1：依据百度地图现有的全景地图进行还是依据现在实际道路的分布进行（因为百度现有全景是2019，现如今真实地图有所改动）**

**问题2：关于细节素材，比如路上的一些公交站台呀 垃圾箱等等 不能完全匹配**

**Comment by donghaiwang** [comment]
是基于最新的实际道路进行建模，百度实景地图只是参考。

细节素材先保证有，然后需要根据现实场景构建素材来建模，保证和真实场景一致。
